### ISSUE TITLE
Experimental dgpu support possible?

### ISSUE THREAD

**Issue by 5l1v3r1** [AlirezaTheH/asus-n550jk-hackintosh#12]
Thank you very much, your settings work flawlessly. Another question, i read opencore-legacy-patcher now works with maxwell nvidia cards (850m is), if we can switch from igpu to dgpu from bios settings ( i think we need a bios modding for that, i saw some gaming laptops has this option) then we might able to get the dgpu work with the latest macos version. It is experimental but do you think that i can be doable ?

**Comment by AlirezaTheH** [comment]
I don't think so. OCLP is more for old real Macs and as far as I know none of them had a GTX Nvidia card. Unfortunately even Intel HD 4600 doesn't work in macOS Ventura!

**Comment by 5l1v3r1** [comment]
Well might be doable because if you realize there is also a mini dp/hdmi port of n500jk and this port might bypass optimus totally if you make the monitor connection through it and after that the only thing needs to be done is to use the opencore legacy patcher to bring nvidia back to it and disable intel igpu. I haven't tried this yet. Most probably i will try because i don't want to build a egpu system just for hackintosh.
