### ISSUE TITLE
Keyboard Backlight

### ISSUE THREAD

**Issue by 5l1v3r1** [AlirezaTheH/asus-n550jk-hackintosh#6]
Can you please explain which kexts you used and which acpi patch you did to achieve keyboard backlight? Secondly for what reason did you use cpufriend kext? I am currently on monterey now and everything is working fine except keyboard backlight. Can you please help with that?

**Comment by AlirezaTheH** [comment]
Hi @5l1v3r1, sorry for the late response.
To enable keyboard backlight you should use `SSDT-ALS0.aml` and `SMCLightSensor.kext`. Also you need to use `SSDT-ASUS-SMC.aml` and `AsusSMC.kext` which enables keyboard hotkeys.
`CPUFriend.kext` and `CPUFriendDataProvider.kext` help CPU to work with better performance and power management.

**Comment by 5l1v3r1** [comment]
Thank you very much, your settings work flawlessly. Another question, i heard opencore-legacy-patcher now works with maxwell nvidia cards (850m is), if we can switch from igpu to dgpu from bios settings ( i think we need a bios modding for that, i saw some gaming laptops has this option) then we might able to get the dgpu work with the latest macos version. It is experimental but do you think that i can be doable ?
